var pos_data = `a : indefinite article, determiner, 
abbreviation : noun, 
ability : noun, 
able : adjective, 
about : preposition, adverb, adjective, 
above : adverb, preposition, adjective, 
abroad : adverb, 
absence : noun, 
absent : adjective, verb, 
accept : verb, 
acceptable : adjective, adverb, noun, 
accident : noun, 
accidental : adjective, adverb, 
accordance : noun, 
according : phrasal verb, 
according to : preposition, 
account : noun, verb, phrasal verb, 
ache : verb, noun, adjective, 
achieve : verb, adjective, phrasal verb, 
achievement : noun, 
acid : noun, adjective, 
across : adverb, preposition, 
act : noun, verb, phrasal verb, 
action : noun, verb, 
active : adjective, adverb, noun, 
activity : noun, 
actor : noun, 
actress : noun, 
actual : adjective, 
actually : adverb, 
add : verb, phrasal verb, 
addition : noun, 
additional : adjective, 
address : noun, verb, 
adjective : noun, adjective, 
admiration : noun, 
admire : verb, 
admit : verb, phrasal verb, 
admittance : noun, 
adult : noun, adjective, 
advance : noun, verb, adjective, 
advanced : adjective, 
advantage : noun, 
adventure : noun, 
adverb : noun, 
advertise : verb, 
advertisement : noun, 
advice : noun, 
advise : verb, 
affair : noun, 
affect : verb, 
afford : verb, adjective, 
afraid : adjective, 
after : preposition, conjunction, adverb, adjective, 
afternoon : noun, interjection, 
afterwards : adverb, preposition, 
again : adverb, 
against : preposition, 
age : noun, verb, 
ago : adverb, 
agree : verb, phrasal verb, 
agreement : noun, 
ahead : adverb, 
aim : noun, verb, 
air : noun, verb, 
aircraft : noun, 
airport : noun, 
alcohol : noun, 
alike : adjective, preposition, adverb, 
alive : adjective, 
all : determiner, predeterminer, pronoun, adverb, 
allow : verb, phrasal verb, 
almost : adverb, 
alone : adjective, adverb, 
along : adverb, preposition, 
aloud : adverb, 
alphabet : noun, 
already : adverb, 
also : adverb, 
although : conjunction, 
altogether : adverb, noun, 
always : adverb, 
am : verb, 
among : preposition, 
amount : noun, verb, phrasal verb, 
amuse : verb, 
amusement : noun, 
amusing : adjective, adverb, noun, 
an : indefinite article, determiner, 
ancient : adjective, noun, 
and : conjunction, 
anger : noun, verb, 
angle : noun, verb, phrasal verb, 
angry : adjective, adverb, 
animal : noun, adjective, 
ankle : noun, 
announce : verb, 
annoy : verb, 
annoyance : noun, 
annoying : adjective, adverb, 
another : determiner, pronoun, 
answer : noun, verb, phrasal verb, 
ant : noun, 
anxiety : noun, 
anxious : adjective, adverb, 
any : determiner, pronoun, adverb, 
anybody : pronoun, 
anyhow : adverb, 
anyone : pronoun, 
anything : pronoun, 
anywhere : adverb, 
apart : adverb, adjective, 
apartment : noun, 
apparatus : noun, 
appear : verb, 
appearance : noun, 
apple : noun, 
appoint : verb, noun, 
approval : noun, 
approve : verb, 
arch : noun, verb, adjective, adverb, 
are : 
area : noun, 
argue : verb, 
argument : noun, 
arm : noun, verb, 
armor : noun, 
armour : noun, 
arms : 
army : noun, 
around : adverb, preposition, 
arrange : verb, 
arrangement : noun, 
arrival : noun, 
arrive : verb, 
art : noun, verb, 
article : noun, 
artificial : adjective, adverb, noun, 
as : preposition, adverb, conjunction, 
as opposed to : 
ash : noun, 
ashamed : adjective, 
aside : adverb, noun, 
ask : verb, phrasal verb, noun, 
asleep : adjective, 
association : noun, 
at : preposition, 
ate : 
atom : noun, 
attack : noun, verb, 
attempt : noun, verb, 
attend : verb, phrasal verb, 
attendance : noun, 
attention : noun, 
attitude : noun, adjective, 
attract : verb, 
attractive : adjective, adverb, noun, 
aunt : noun, 
authority : noun, 
autumn : noun, 
available : adjective, noun, 
average : adjective, noun, verb, phrasal verb, 
avoid : verb, 
awake : adjective, verb, phrasal verb, 
away : adverb, adjective, 
awkward : adjective, adverb, noun, 
baby : noun, verb, 
back : adverb, noun, verb, phrasal verb, adjective, 
background : noun, 
backward : adjective, noun, 
backwards : adverb, 
bacteria : noun, adjective, 
bad : adjective, noun, adverb, 
bag : noun, verb, phrasal verb, 
bake : verb, 
balance : noun, verb, phrasal verb, 
ball : noun, verb, 
banana : noun, 
band : noun, verb, phrasal verb, 
bank : noun, verb, phrasal verb, 
bar : noun, verb, preposition, 
bare : adjective, noun, verb, adverb, 
barrel : noun, verb, 
base : verb, phrasal verb, noun, adjective, 
basic : adjective, 
basket : noun, 
bath : noun, verb, 
bathe : verb, noun, 
battle : noun, verb, 
be : auxiliary verb, 
beach : noun, verb, 
beak : noun, 
beam : noun, verb, 
bean : noun, verb, 
bear : verb, phrasal verb, noun, 
beard : noun, adjective, verb, 
beat : verb, phrasal verb, noun, adjective, 
beaten : adjective, 
beautiful : adjective, adverb, 
beauty : noun, adjective, 
became : 
because : conjunction, preposition, 
become : verb, 
bed : noun, verb, phrasal verb, 
bee : noun, 
been : phrasal verb, 
beer : noun, adjective, 
before : conjunction, preposition, adverb, 
beg : verb, 
began : verb, 
begin : verb, phrasal verb, 
beginning : noun, 
begun : verb, 
behave : verb, 
behavior : noun, adjective, adverb, 
behaviour : noun, adjective, adverb, 
behind : preposition, adverb, noun, 
being : verb, noun, 
belief : noun, 
believe : verb, phrasal verb, 
bell : noun, 
belong : verb, noun, phrasal verb, 
below : adverb, preposition, 
belt : noun, verb, phrasal verb, 
bend : verb, noun, 
beneath : adverb, preposition, 
bent : adjective, noun, 
berry : noun, 
beside : preposition, adverb, adjective, 
besides : adverb, preposition, 
best : adjective, adverb, noun, verb, 
better : adjective, adverb, noun, verb, 
between : adverb, preposition, 
beyond : preposition, adverb, noun, 
bicycle : noun, verb, 
big : adjective, verb, phrasal verb, 
bill : noun, verb, phrasal verb, 
bind : verb, phrasal verb, noun, 
bird : noun, 
birth : noun, 
birthday : noun, 
bit : adverb, pronoun, noun, 
bite : verb, phrasal verb, noun, 
bitten : verb, phrasal verb, adjective, 
bitter : adjective, noun, 
black : adjective, noun, verb, phrasal verb, 
blade : noun, 
blame : verb, noun, 
bled : verb, 
bleed : verb, 
bless : verb, 
blew : verb, 
blind : adjective, noun, verb, adverb, 
block : noun, verb, phrasal verb, 
blood : noun, verb, 
blow : verb, phrasal verb, noun, 
blue : adjective, noun, 
board : noun, verb, phrasal verb, 
boat : noun, 
body : noun, 
boil : verb, phrasal verb, noun, 
bomb : noun, verb, phrasal verb, 
bone : noun, verb, phrasal verb, 
book : noun, verb, phrasal verb, 
boot : noun, verb, phrasal verb, 
border : noun, verb, phrasal verb, 
bore : verb, noun, 
bored : adjective, 
boring : adjective, 
born : verb, adjective, 
borne : adjective, 
borrow : verb, 
both : determiner, predeterminer, pronoun, conjunction, 
bottle : noun, verb, phrasal verb, 
bottom : noun, adjective, verb, phrasal verb, 
bought : verb, 
bound : adjective, verb, noun, 
bowels : noun, 
bowl : noun, verb, phrasal verb, 
box : noun, verb, phrasal verb, 
boy : noun, interjection, 
brain : noun, verb, 
branch : noun, verb, phrasal verb, 
brass : noun, 
brave : adjective, adverb, verb, noun, 
bread : noun, 
breadth : noun, 
break : verb, phrasal verb, noun, 
breakfast : noun, verb, 
breast : noun, verb, 
breath : noun, 
breathe : verb, phrasal verb, 
bred : verb, 
breed : verb, noun, 
brick : noun, verb, phrasal verb, 
bridge : noun, verb, 
bright : adjective, adverb, noun, 
bring : verb, phrasal verb, 
broad : adjective, noun, 
broadcast : noun, verb, 
broke : adjective, 
broken : adjective, 
brother : noun, interjection, 
brought : verb, phrasal verb, 
brown : adjective, noun, verb, 
brush : noun, verb, phrasal verb, 
bucket : noun, verb, phrasal verb, 
build : verb, phrasal verb, noun, 
building : noun, 
built : adjective, 
bullet : noun, 
bunch : noun, verb, 
burial : noun, 
burn : verb, phrasal verb, noun, 
burnt : adjective, 
burst : verb, phrasal verb, noun, 
bury : verb, 
bus : noun, verb, 
bush : noun, 
business : noun, 
busy : adjective, verb, 
but : conjunction, preposition, adverb, noun, 
butter : noun, adjective, verb, phrasal verb, 
button : noun, verb, 
buy : verb, phrasal verb, noun, 
by : preposition, adverb, 
cage : noun, verb, 
cake : noun, verb, 
calculate : verb, phrasal verb, 
calculator : noun, 
call : verb, phrasal verb, noun, 
calm : adjective, adverb, noun, verb, 
came : verb, phrasal verb, 
camera : noun, 
camp : noun, verb, phrasal verb, adjective, 
can : modal verb, noun, 
candle : noun, 
cannot : modal verb, 
cap : noun, verb, 
capital : noun, adjective, 
captain : noun, verb, 
car : noun, 
card : noun, verb, 
cardboard : noun, adjective, 
care : noun, verb, phrasal verb, 
careful : adjective, noun, 
carefully : adverb, 
careless : adjective, adverb, noun, 
carriage : noun, 
carry : verb, phrasal verb, noun, 
cart : noun, verb, phrasal verb, 
case : noun, verb, 
castle : noun, 
cat : noun, 
catch : verb, phrasal verb, noun, 
cattle : noun, 
caught : verb, phrasal verb, 
cause : noun, verb, 
ceiling : noun, 
celebrate : verb, 
cell : noun, 
cement : noun, verb, 
cent : noun, 
center : noun, verb, phrasal verb, 
centimeter : noun, 
centimetre : noun, 
central : adjective, adverb, noun, 
centre : noun, verb, phrasal verb, 
century : noun, 
ceremony : noun, 
certain : adjective, pronoun, 
chain : noun, verb, 
chair : noun, verb, 
chairperson : noun, 
chalk : noun, verb, phrasal verb, 
chance : noun, verb, phrasal verb, adjective, 
change : verb, phrasal verb, noun, 
character : noun, 
charge : noun, verb, 
charm : noun, verb, 
chase : verb, phrasal verb, noun, 
cheap : adjective, adverb, noun, 
cheat : verb, phrasal verb, noun, 
check : verb, phrasal verb, noun, 
cheek : noun, verb, 
cheer : noun, verb, adjective, phrasal verb, 
cheerful : adjective, adverb, noun, 
cheese : noun, 
chemical : noun, adjective, adverb, 
chemistry : noun, 
cheque : noun, 
chest : noun, 
chicken : noun, verb, phrasal verb, adjective, 
chief : adjective, noun, 
child : noun, 
childhood : noun, 
children : noun, 
chimney : noun, 
chin : noun, 
chocolate : noun, 
choice : noun, adjective, 
choose : verb, 
chose : verb, 
chosen : verb, adjective, 
church : noun, 
cigarette : noun, 
cinema : noun, 
circle : noun, verb, 
circular : adjective, noun, 
citizen : noun, 
city : noun, adjective, 
civilization : noun, 
claim : verb, noun, 
class : noun, verb, 
clay : noun, 
clean : adjective, noun, verb, phrasal verb, adverb, 
clear : adjective, noun, verb, phrasal verb, adverb, 
clerk : noun, verb, 
clever : adjective, adverb, noun, 
cliff : noun, 
climb : verb, phrasal verb, noun, 
clock : noun, verb, phrasal verb, 
clockwork : noun, 
close : verb, phrasal verb, adjective, noun, preposition, adverb, 
cloth : noun, 
clothes : noun, 
clothing : noun, 
cloud : noun, verb, phrasal verb, 
club : noun, verb, phrasal verb, 
coal : noun, 
coast : noun, verb, 
coat : noun, verb, 
coffee : noun, 
coin : noun, verb, 
cold : adjective, noun, adverb, 
collar : noun, verb, 
collect : verb, phrasal verb, adverb, noun, 
college : noun, 
color : verb, noun, adjective, 
colour : noun, verb, adjective, 
comb : noun, verb, phrasal verb, 
combination : noun, 
combine : verb, noun, 
come : verb, phrasal verb, noun, 
comfort : noun, verb, 
comfortable : adjective, 
command : noun, verb, 
committee : noun, 
common : adjective, noun, 
communicate : verb, 
communication : noun, 
companion : noun, 
company : noun, 
compare : verb, noun, 
comparison : noun, 
compete : verb, 
competition : noun, 
competitor : noun, 
complain : verb, phrasal verb, 
complaint : noun, 
complete : adjective, noun, verb, 
completely : adverb, 
complicated : adjective, 
compound : noun, verb, adjective, 
computer : noun, 
concern : noun, verb, 
concerning : preposition, 
concert : noun, 
condition : noun, verb, 
confidence : noun, 
confident : adjective, adverb, noun, 
confuse : verb, 
confusing : adjective, adverb, 
connect : verb, phrasal verb, 
connection : noun, 
conscience : noun, 
conscious : adjective, adverb, 
consider : verb, 
consist : verb, phrasal verb, 
consist of : phrasal verb, 
consonant : noun, adjective, 
contain : verb, 
container : noun, 
contents : noun, 
continue : verb, 
continuous : adjective, adverb, 
contract : noun, verb, phrasal verb, 
control : noun, verb, 
convenient : adjective, 
conversation : noun, 
cook : verb, phrasal verb, noun, 
cool : adjective, noun, adverb, verb, phrasal verb, 
copper : noun, adjective, 
copy : noun, verb, phrasal verb, 
cord : noun, adjective, 
corn : noun, 
corner : noun, verb, 
correct : adjective, adverb, noun, verb, 
cost : noun, verb, 
cotton : noun, verb, phrasal verb, 
cough : verb, phrasal verb, noun, 
could : modal verb, 
council : noun, 
count : verb, phrasal verb, noun, 
country : noun, adjective, 
countryside : noun, adjective, 
courage : noun, 
course : noun, verb, 
court : noun, verb, 
cover : verb, phrasal verb, noun, 
cow : noun, verb, 
coward : noun, adjective, 
cowardly : adjective, adverb, 
crack : verb, phrasal verb, noun, adjective, 
crash : verb, phrasal verb, noun, 
crazy : adjective, adverb, noun, 
cream : noun, adjective, verb, phrasal verb, 
creature : noun, 
creep : verb, phrasal verb, noun, 
crept : verb, phrasal verb, 
cricket : noun, 
cried : verb, phrasal verb, 
cries : verb, phrasal verb, 
crime : noun, 
criminal : adjective, adverb, noun, 
criticism : noun, 
criticize : verb, 
crop : noun, verb, phrasal verb, 
cross : verb, phrasal verb, noun, adjective, adverb, 
crowd : noun, verb, phrasal verb, 
cruel : adjective, adverb, 
cruelty : noun, 
crush : verb, phrasal verb, noun, 
cry : verb, phrasal verb, noun, 
cultivate : verb, 
cup : noun, verb, 
cupboard : noun, 
cure : noun, verb, 
curl : verb, phrasal verb, noun, 
current : adjective, noun, 
curse : verb, phrasal verb, noun, 
curtain : noun, verb, phrasal verb, 
curve : noun, verb, 
custom : noun, adjective, 
customer : noun, 
cut : verb, phrasal verb, noun, 
cycle : noun, verb, 
daily : adjective, adverb, noun, 
damage : noun, verb, 
dance : noun, verb, 
danger : noun, 
dangerous : adjective, adverb, 
dare : verb, modal verb, noun, 
daring : adjective, adverb, noun, 
dark : adjective, noun, 
date : noun, verb, phrasal verb, 
daughter : noun, 
day : noun, 
dead : adjective, noun, adverb, 
deal : noun, verb, phrasal verb, 
deal with : phrasal verb, 
dealt : verb, phrasal verb, 
dealt with : phrasal verb, 
dear : interjection, noun, adjective, adverb, 
death : noun, 
debt : noun, 
decay : verb, noun, 
deceit : noun, 
deceive : verb, noun, 
decide : verb, phrasal verb, 
decimal : noun, adjective, 
decision : noun, 
declaration : noun, 
declare : verb, phrasal verb, 
decorate : verb, noun, 
decoration : noun, 
decrease : verb, noun, 
deep : adjective, adverb, noun, 
deer : noun, 
defeat : noun, verb, 
defence : noun, 
defend : verb, 
defense : noun, 
definite : adjective, 
definitely : adverb, 
degree : noun, 
delay : noun, verb, adjective, 
deliberate : adjective, noun, verb, 
deliberately : adverb, 
delicate : adjective, adverb, 
delight : noun, verb, phrasal verb, 
deliver : verb, noun, phrasal verb, 
demand : noun, verb, 
department : noun, adjective, 
depend : verb, phrasal verb, 
dependent : noun, adjective, 
depth : noun, 
descend : verb, phrasal verb, 
describe : verb, 
description : noun, 
descriptive : adjective, adverb, 
desert : noun, verb, 
deserve : verb, 
design : noun, verb, 
desirable : adjective, adverb, noun, 
desire : noun, verb, adjective, 
desk : noun, 
destroy : verb, 
destruction : noun, 
detail : noun, verb, 
determination : noun, 
determined : adjective, 
develop : verb, 
devil : noun, 
diamond : noun, 
dictionary : noun, 
did : auxiliary verb, phrasal verb, 
die : verb, phrasal verb, noun, 
difference : noun, 
different : adjective, adverb, 
difficult : adjective, 
difficulty : noun, 
dig : verb, phrasal verb, noun, 
dinner : noun, 
dip : verb, phrasal verb, noun, 
direct : adjective, verb, adverb, 
direction : noun, 
dirt : noun, 
dirty : adjective, adverb, verb, 
dis- : prefix, 
disappoint : verb, 
disappointing : adjective, adverb, 
discourage : verb, 
discouragement : noun, 
discover : verb, noun, 
discovery : noun, 
discuss : verb, 
discussion : noun, 
disease : noun, adjective, 
dish : noun, verb, phrasal verb, 
dismiss : verb, 
distance : noun, verb, 
distant : adjective, adverb, 
ditch : noun, verb, 
divide : verb, adjective, noun, 
division : noun, 
do : auxiliary verb, phrasal verb, noun, 
doctor : noun, verb, 
document : noun, verb, 
does : auxiliary verb, phrasal verb, 
dog : noun, verb, 
doing : noun, 
dollar : noun, 
done : adjective, interjection, 
door : noun, verb, 
doorway : noun, 
dot : noun, verb, 
double : adjective, noun, verb, phrasal verb, adverb, predeterminer, 
doubt : noun, verb, 
down : adverb, preposition, adjective, verb, noun, 
drag : verb, phrasal verb, noun, 
drank : verb, phrasal verb, 
draw : verb, phrasal verb, noun, 
drawer : noun, 
drawn : adjective, 
dream : noun, verb, phrasal verb, 
dreamt : verb, phrasal verb, 
dress : noun, verb, phrasal verb, 
drew : verb, phrasal verb, 
dried : adjective, 
dries : noun, verb, phrasal verb, 
drink : verb, phrasal verb, noun, 
drive : verb, phrasal verb, noun, 
driven : adjective, 
drop : verb, phrasal verb, noun, 
drove : noun, 
drown : verb, 
drug : noun, verb, adjective, 
drum : noun, verb, phrasal verb, 
drunk : adjective, noun, verb, phrasal verb, 
dry : adjective, noun, verb, phrasal verb, 
duck : noun, verb, phrasal verb, 
dug : verb, phrasal verb, 
dull : adjective, adverb, noun, verb, 
during : preposition, 
dust : noun, verb, phrasal verb, 
duty : noun, 
dying : adjective, 
each : determiner, pronoun, adverb, 
eager : adjective, adverb, noun, 
ear : noun, 
early : adjective, adverb, 
earn : verb, 
earth : noun, verb, 
easily : adverb, 
east : noun, adjective, adverb, 
eastern : adjective, 
easy : adjective, adverb, 
eat : verb, phrasal verb, 
eaten : verb, phrasal verb, 
economic : adjective, 
edge : noun, verb, phrasal verb, 
educate : verb, 
educated : adjective, 
education : noun, 
effect : noun, verb, 
effective : adjective, noun, 
effort : noun, 
egg : noun, verb, phrasal verb, 
eight : number, noun, 
eighth : adjective, pronoun, noun, 
either : conjunction, determiner, pronoun, adverb, 
elastic : noun, adjective, 
elbow : noun, verb, 
elect : verb, adjective, 
election : noun, 
electric : adjective, 
electricity : noun, 
electronic : adjective, adverb, 
elephant : noun, 
else : adverb, 
embarrass : verb, 
embarrassing : adjective, adverb, 
emotion : noun, 
emphasize : verb, 
employ : verb, noun, 
employer : noun, 
employment : noun, 
empty : adjective, adverb, verb, phrasal verb, 
enclose : verb, 
enclosure : noun, 
encourage : verb, adjective, 
encouragement : noun, 
end : noun, verb, phrasal verb, 
enemy : noun, 
energy : noun, 
engine : noun, 
engineer : noun, verb, 
english : noun, adjective, 
enjoy : verb, 
enjoyable : adjective, adverb, 
enjoyment : noun, 
enough : adverb, determiner, pronoun, 
enter : verb, phrasal verb, 
entertain : verb, 
entertainment : noun, 
entrance : noun, verb, adjective, 
envelope : noun, 
environment : noun, adjective, prefix, 
equal : adjective, verb, noun, 
equality : noun, 
equipment : noun, 
escape : verb, noun, 
especially : adverb, 
establish : verb, 
establishment : noun, 
even : adverb, adjective, noun, verb, phrasal verb, 
evening : noun, interjection, 
event : noun, 
ever : adverb, 
every : determiner, 
everybody : pronoun, 
everyone : pronoun, 
everything : pronoun, 
everywhere : adverb, preposition, adjective, 
evil : adjective, adverb, noun, 
exact : adjective, noun, verb, 
exactly : adverb, 
examination : noun, 
examine : verb, 
example : noun, 
excellent : adjective, adverb, 
except : conjunction, preposition, verb, 
exchange : noun, verb, adjective, 
excite : verb, 
excited : adjective, adverb, 
exciting : adjective, adverb, 
excuse : verb, noun, 
exercise : noun, verb, 
exist : verb, 
existence : noun, 
expect : verb, 
expensive : adjective, adverb, 
experience : noun, verb, 
explain : verb, phrasal verb, 
explanation : noun, 
explode : verb, phrasal verb, 
explosion : noun, 
explosive : adjective, adverb, noun, 
express : verb, adjective, noun, adverb, 
expression : noun, 
extreme : adjective, noun, 
extremely : adverb, 
eye : noun, verb, phrasal verb, 
eyelid : noun, 
face : noun, verb, phrasal verb, 
fact : noun, 
factory : noun, 
fail : verb, noun, 
failure : noun, 
faint : adjective, adverb, noun, verb, 
fair : adjective, noun, adverb, 
fairly : adverb, 
fairy : noun, 
faith : noun, 
faithful : adjective, noun, 
fall : verb, phrasal verb, noun, 
fallen : adjective, 
false : adjective, 
fame : noun, 
familiar : adjective, noun, 
family : noun, 
famous : adjective, noun, 
fancy : verb, noun, adjective, 
far : adverb, adjective, 
farm : noun, adjective, verb, phrasal verb, 
farmer : noun, 
farmyard : noun, 
fashion : noun, verb, 
fashionable : adjective, adverb, verb phrase, 
fast : adverb, adjective, verb, noun, 
fasten : verb, phrasal verb, 
fat : adjective, noun, 
fate : noun, 
father : noun, verb, phrasal verb, 
fault : noun, verb, 
favor : noun, verb, phrasal verb, 
favorable : adjective, adverb, 
favorite : adjective, noun, 
favour : noun, verb, phrasal verb, 
favourable : adjective, adverb, 
favourite : adjective, noun, 
fear : noun, verb, 
feather : noun, verb, 
feature : noun, verb, 
fed : noun, 
feed : verb, phrasal verb, noun, 
feel : verb, phrasal verb, noun, 
feeling : noun, adjective, adverb, 
feelings : noun, 
feet : noun, 
fell : noun, verb, adjective, 
fellow : noun, adjective, 
felt : noun, 
female : adjective, noun, 
fence : noun, verb, phrasal verb, 
fever : noun, 
few : determiner, pronoun, adjective, 
field : noun, verb, 
fierce : adjective, adverb, noun, 
fifth : adjective, pronoun, adverb, noun, 
fight : verb, phrasal verb, noun, 
figure : noun, verb, phrasal verb, 
fill : verb, phrasal verb, noun, 
film : noun, verb, phrasal verb, 
final : adjective, noun, 
finally : adverb, 
financial : adjective, adverb, 
find : verb, phrasal verb, noun, 
find out : phrasal verb, 
fine : adjective, adverb, verb, noun, 
finger : noun, verb, 
finish : verb, phrasal verb, noun, 
fire : noun, verb, phrasal verb, 
fireplace : noun, 
firm : noun, adjective, adverb, verb, phrasal verb, 
first : adjective, adverb, noun, pronoun, 
fish : noun, verb, phrasal verb, 
fisherman : noun, 
fishermen : noun, 
fit : verb, phrasal verb, adjective, noun, 
five : number, noun, 
fix : verb, phrasal verb, noun, 
flag : noun, verb, phrasal verb, 
flame : noun, verb, 
flash : verb, phrasal verb, noun, adjective, 
flat : adjective, noun, adverb, 
flesh : noun, verb, phrasal verb, 
flew : verb, phrasal verb, 
flies : verb, phrasal verb, noun, 
flight : noun, 
float : verb, phrasal verb, noun, 
flood : verb, phrasal verb, noun, 
floor : noun, verb, 
flour : noun, verb, 
flow : noun, verb, 
flower : noun, verb, 
flown : verb, phrasal verb, 
fly : verb, phrasal verb, noun, adjective, 
fold : verb, phrasal verb, noun, 
follow : verb, phrasal verb, 
fond : adjective, noun, 
food : noun, 
fool : noun, verb, phrasal verb, adjective, 
foolish : adjective, adverb, noun, 
foot : noun, verb, 
football : noun, 
footpath : noun, 
footstep : noun, 
for : preposition, conjunction, 
forbade : verb, 
forbid : verb, 
forbidden : adjective, 
force : noun, verb, phrasal verb, 
forehead : noun, 
foreign : adjective, noun, 
foreigner : noun, 
forest : noun, 
forgave : verb, 
forget : verb, 
forgive : verb, 
forgiven : adjective, 
forgot : verb, 
forgotten : verb, adjective, 
fork : noun, verb, phrasal verb, 
form : noun, verb, 
formal : adjective, noun, 
former : adjective, noun, 
formerly : adverb, 
fort : noun, 
fortunate : adjective, 
fortune : noun, 
forward : adverb, adjective, verb, noun, 
forwards : adverb, 
fought : verb, phrasal verb, 
found : verb, noun, 
found out : phrasal verb, 
four : number, noun, 
fourth : adjective, adverb, pronoun, noun, 
fox : noun, verb, 
frame : noun, verb, 
free : adjective, verb, adverb, noun, 
freedom : noun, 
freeze : verb, phrasal verb, noun, 
frequent : adjective, verb, 
fresh : adjective, noun, adverb, 
friend : noun, verb, 
friendly : adjective, noun, 
frighten : verb, phrasal verb, 
frightening : adjective, adverb, 
from : preposition, 
front : noun, adjective, verb, 
froze : verb, phrasal verb, 
frozen : adjective, 
fruit : noun, verb, 
fulfil : verb, 
fulfill : verb, 
full : adjective, noun, adverb, 
fun : noun, adjective, 
funeral : noun, 
funny : adjective, noun, 
fur : noun, verb, adjective, 
furnish : verb, adjective, 
furniture : noun, 
further : adverb, adjective, verb, 
future : adjective, noun, 
gain : verb, phrasal verb, noun, 
game : noun, adjective, adverb, verb, 
garage : noun, verb, 
garden : noun, verb, 
garment : noun, 
gas : noun, verb, phrasal verb, 
gate : noun, verb, 
gather : verb, noun, 
gave : verb, phrasal verb, 
general : adjective, noun, 
generally : adverb, 
generous : adjective, adverb, 
gentle : adjective, noun, 
gentleman : noun, 
gentlemen : noun, 
get : verb, phrasal verb, 
gift : noun, 
girl : noun, 
give : verb, phrasal verb, noun, 
given : adjective, preposition, noun, 
glad : adjective, noun, 
glass : noun, verb, phrasal verb, 
glory : noun, verb, phrasal verb, 
glue : noun, verb, 
go : verb, phrasal verb, noun, 
goat : noun, 
god : noun, adjective, 
goes : verb, phrasal verb, noun, 
going : noun, adjective, 
gold : noun, adjective, 
golden : adjective, 
gone : adjective, preposition, 
good : adjective, noun, adverb, 
goodbye : interjection, noun, 
goods : noun, 
got : verb, phrasal verb, 
gotten : preposition, 
govern : verb, 
government : noun, adjective, 
grace : noun, verb, 
graceful : adjective, adverb, noun, 
gradual : adjective, 
grain : noun, 
gram : noun, 
grammar : noun, 
grand : noun, adjective, adverb, 
grandfather : noun, 
grandmother : noun, 
grandparent : noun, 
grass : noun, verb, phrasal verb, 
grateful : adjective, adverb, 
grave : noun, adjective, adverb, 
gray : noun, verb, 
great : adjective, noun, 
green : adjective, noun, verb, 
greet : verb, 
greeting : noun, 
grew : verb, phrasal verb, 
grey : adjective, noun, verb, 
grief : noun, 
grieve : verb, 
ground : noun, verb, phrasal verb, adjective, 
group : noun, verb, 
grow : verb, phrasal verb, 
grown : adjective, 
growth : noun, 
guard : noun, verb, phrasal verb, 
guess : verb, noun, 
guest : noun, adjective, verb, 
guidance : noun, 
guide : noun, verb, 
guilt : noun, verb, phrasal verb, 
guilty : adjective, adverb, 
gun : noun, verb, phrasal verb, 
habit : noun, 
habitual : adjective, adverb, 
had : auxiliary verb, phrasal verb, 
hair : noun, 
hairy : adjective, noun, 
half : predeterminer, pronoun, adjective, noun, adverb, 
hall : noun, 
halves : 
hammer : noun, verb, phrasal verb, 
hand : noun, verb, phrasal verb, 
handkerchief : noun, 
handle : verb, noun, 
hang : verb, phrasal verb, noun, 
hanged : 
happen : verb, phrasal verb, 
happy : adjective, 
hard : adjective, noun, adverb, 
harden : verb, 
hardly : adverb, 
hardship : noun, 
harm : noun, verb, 
harmful : adjective, 
harmless : adjective, adverb, noun, 
has : auxiliary verb, phrasal verb, 
hasty : adjective, 
hat : noun, 
hate : verb, adjective, noun, 
hatred : noun, 
have : auxiliary verb, phrasal verb, 
he : pronoun, noun, 
head : noun, verb, phrasal verb, 
health : noun, 
healthy : adjective, adverb, noun, 
hear : verb, adjective, phrasal verb, 
heard : 
heart : noun, 
heat : noun, verb, phrasal verb, 
heaven : noun, 
heavy : adjective, noun, adverb, 
heel : noun, verb, phrasal verb, 
height : noun, 
held : 
hello : interjection, noun, 
help : verb, phrasal verb, noun, 
helpful : adjective, adverb, noun, 
hen : noun, 
her : determiner, pronoun, 
here : adverb, 
hers : pronoun, 
herself : pronoun, 
hid : 
hidden : adjective, 
hide : verb, noun, 
high : adjective, adverb, noun, 
hill : noun, 
him : pronoun, 
himself : pronoun, 
hire : verb, phrasal verb, noun, 
his : determiner, pronoun, 
historical : adjective, adverb, 
history : noun, 
hit : verb, phrasal verb, noun, 
hold : verb, phrasal verb, noun, 
hole : noun, verb, phrasal verb, 
holiday : noun, verb, 
hollow : adjective, adverb, noun, verb, phrasal verb, 
holy : adjective, 
home : noun, adverb, adjective, verb, phrasal verb, 
honest : adjective, 
honesty : noun, 
honor : noun, verb, 
honorable : adjective, adverb, 
honour : noun, verb, 
honourable : adjective, adverb, 
hook : noun, verb, phrasal verb, 
hope : verb, noun, 
hopeful : adjective, noun, 
hopeless : adjective, noun, 
horizon : noun, 
horn : noun, verb, phrasal verb, 
horse : noun, verb, phrasal verb, 
hospital : noun, 
host : noun, verb, 
hot : adjective, verb, phrasal verb, 
hotel : noun, 
hour : noun, 
hourly : adjective, adverb, 
house : noun, verb, 
how : adverb, 
human : adjective, noun, 
humor : noun, verb, 
humorous : adjective, adverb, noun, 
humour : noun, verb, 
hundred : number, noun, adjective, 
hundredth : 
hung : 
hunger : noun, verb, phrasal verb, 
hungry : adjective, 
hunt : verb, phrasal verb, noun, 
hurry : verb, phrasal verb, noun, 
hurt : verb, adjective, noun, 
husband : noun, verb, 
hut : noun, 
i : pronoun, noun, 
ice : noun, verb, phrasal verb, 
icy : adjective, noun, 
idea : noun, 
if : conjunction, noun, 
ignore : verb, 
ill : adjective, adverb, noun, 
illegal : adjective, adverb, noun, 
illness : noun, 
im- : prefix, 
image : noun, 
imaginary : adjective, 
imagination : noun, 
imagine : verb, 
immediately : adverb, conjunction, 
importance : noun, 
important : adjective, 
impressive : adjective, adverb, noun, 
improve : verb, phrasal verb, 
improvement : noun, 
in : preposition, adverb, adjective, verb phrase, noun, 
in spite of : 
in- : prefix, 
include : verb, 
including : preposition, 
income : noun, 
increase : verb, adjective, noun, 
independent : adjective, adverb, 
indoor : adjective, 
indoors : adverb, 
industrial : adjective, adverb, 
industry : noun, 
infect : verb, 
infection : noun, 
infectious : adjective, adverb, 
influence : noun, verb, 
influential : adjective, 
inform : verb, phrasal verb, 
information : noun, adjective, 
injure : verb, 
injury : noun, 
ink : noun, verb, phrasal verb, 
inner : adjective, 
inquire : verb, noun, phrasal verb, 
inquiry : noun, 
insect : noun, 
inside : adverb, preposition, noun, adjective, 
instead : adverb, 
institution : noun, 
instruct : verb, 
instruction : noun, 
instrument : noun, 
insult : verb, noun, 
insulting : adjective, adverb, 
insurance : noun, 
insure : verb, phrasal verb, 
intelligence : noun, 
intelligent : adjective, adverb, 
intend : verb, 
intention : noun, 
interest : noun, verb, 
interesting : adjective, 
international : adjective, noun, 
interrupt : verb, noun, 
into : preposition, 
introduce : verb, 
introduction : noun, 
invent : verb, 
invention : noun, 
invitation : noun, 
invite : verb, phrasal verb, noun, 
involve : verb, 
inward : adjective, adverb, 
ir- : prefix, 
iron : noun, verb, phrasal verb, adjective, 
is : 
island : noun, 
it : pronoun, adjective, 
its : determiner, 
itself : pronoun, 
jaw : noun, verb, 
jealous : adjective, 
jealousy : noun, 
jelly : noun, 
jewel : noun, 
jewellery : noun, 
jewelry : noun, 
job : noun, 
join : verb, phrasal verb, noun, 
joint : adjective, adverb, noun, verb, 
joke : noun, verb, adverb, 
journey : noun, verb, 
joy : noun, verb, 
judge : noun, verb, 
judgment : noun, 
juice : noun, verb, phrasal verb, 
jump : verb, phrasal verb, noun, 
just : adverb, adjective, 
justice : noun, 
keen : adjective, adverb, noun, verb, 
keep : verb, phrasal verb, noun, 
kept : 
key : adjective, noun, verb, phrasal verb, 
kick : verb, phrasal verb, noun, 
kill : verb, phrasal verb, noun, 
kilo : noun, 
kilogram : noun, 
kilometer : noun, 
kilometre : noun, 
kind : noun, adjective, 
king : noun, 
kingdom : noun, 
kiss : verb, phrasal verb, noun, 
kitchen : noun, 
knee : noun, verb, 
kneel : verb, 
knelt : 
knew : 
knife : noun, verb, 
knock : verb, phrasal verb, noun, 
knot : noun, verb, 
know : verb, noun, adjective, verb phrase, 
knowledge : noun, 
known : adjective, 
labor : noun, verb, 
labour : noun, verb, 
lack : noun, verb, 
ladder : noun, verb, 
lady : noun, 
laid : 
lain : 
lain down : 
lake : noun, 
lamb : noun, verb, 
lamp : noun, 
land : noun, verb, phrasal verb, 
language : noun, 
large : adjective, verb, 
last : determiner, adjective, adverb, noun, pronoun, verb, 
late : adjective, noun, adverb, 
lately : adverb, 
laugh : verb, phrasal verb, noun, 
laughter : noun, 
law : noun, 
lawyer : noun, 
lay : verb, phrasal verb, adjective, noun, 
lay down : phrasal verb, 
layer : noun, verb, 
lazy : adjective, adverb, noun, 
lead : verb, phrasal verb, noun, 
leaf : noun, verb, phrasal verb, 
lean : verb, phrasal verb, adjective, noun, 
learn : verb, 
learnt : 
least : determiner, pronoun, adverb, 
leather : noun, 
leave : verb, phrasal verb, noun, 
leaves : 
led : 
left : adjective, adverb, noun, 
leg : noun, verb, 
legal : adjective, 
lend : verb, 
length : noun, 
lent : 
less : adverb, determiner, pronoun, preposition, 
lesson : noun, 
let : verb, phrasal verb, noun, 
let go of : 
letter : noun, verb, 
level : noun, adjective, verb, phrasal verb, 
library : noun, 
lid : noun, 
lie : verb, phrasal verb, noun, 
lie down : phrasal verb, noun, 
lied : 
life : noun, 
lift : verb, phrasal verb, noun, 
light : noun, adjective, verb, phrasal verb, adverb, 
lightning : noun, adjective, 
like : preposition, verb, noun, adverb, conjunction, adjective, 
likely : adjective, adverb, 
limb : noun, 
limit : noun, verb, 
line : noun, verb, phrasal verb, 
lion : noun, 
lip : noun, 
liquid : noun, adjective, 
list : noun, verb, 
listen : verb, phrasal verb, noun, 
lit : 
liter : noun, 
literature : noun, 
litre : noun, 
little : adjective, determiner, pronoun, adverb, 
live : verb, phrasal verb, adjective, adverb, 
lives : noun, 
load : noun, verb, phrasal verb, 
loaf : noun, verb, 
loaves : noun, 
local : adjective, noun, 
lock : verb, adjective, phrasal verb, noun, 
lodging : noun, 
lodgings : 
log : noun, verb, phrasal verb, 
lonely : adjective, noun, 
long : adjective, adverb, verb, 
look : verb, phrasal verb, noun, 
look after : phrasal verb, 
look for : phrasal verb, 
look up : phrasal verb, 
loose : adjective, adverb, noun, verb, phrasal verb, 
lord : noun, verb, 
lose : verb, phrasal verb, 
loss : noun, 
lost : adjective, 
lot : pronoun, adverb, noun, 
loud : adjective, adverb, noun, 
love : verb, noun, 
low : adjective, noun, adverb, verb, 
lower : adjective, verb, 
loyal : adjective, adverb, 
loyalty : noun, 
luck : noun, verb, phrasal verb, 
lucky : adjective, 
lump : noun, verb, 
lung : noun, 
lying : verb, 
lying down : 
machine : noun, verb, 
machinery : noun, 
mad : adjective, 
made : verb, 
made into : 
made up : 
magazine : noun, 
magic : noun, adjective, verb, phrasal verb, 
magician : noun, 
mail : noun, verb, phrasal verb, 
main : adjective, noun, 
make : verb, phrasal verb, noun, 
make into : phrasal verb, 
make up : phrasal verb, 
male : adjective, noun, 
man : noun, adjective, verb, interjection, 
manage : verb, 
manager : noun, 
manner : noun, 
many : determiner, pronoun, adjective, 
map : noun, verb, phrasal verb, 
march : verb, noun, 
mark : noun, verb, phrasal verb, 
market : noun, verb, 
marriage : noun, 
married : adjective, 
marry : verb, phrasal verb, 
mass : noun, adjective, verb, 
master : noun, verb, adjective, 
mat : noun, adjective, 
match : noun, verb, phrasal verb, 
material : noun, adjective, 
mathematics : noun, 
matter : noun, verb, 
may : modal verb, noun, 
maybe : adverb, 
me : pronoun, 
meal : noun, 
mean : verb, adjective, adverb, noun, 
meaning : noun, 
means : noun, 
meant : 
measure : verb, phrasal verb, noun, 
measurement : noun, 
meat : noun, 
medical : adjective, adverb, noun, 
medicine : noun, 
meet : verb, phrasal verb, noun, adjective, 
meeting : noun, 
melt : verb, phrasal verb, 
member : noun, 
memory : noun, 
men : noun, 
mend : verb, noun, 
mental : adjective, adverb, 
mention : verb, noun, 
merry : adjective, noun, 
message : noun, 
messenger : noun, verb, 
met : 
metal : noun, 
meter : noun, verb, 
method : noun, 
metre : noun, 
metric : adjective, 
mice : noun, 
microscope : noun, 
middle : noun, adjective, 
might : modal verb, noun, 
mile : noun, 
military : adjective, adverb, noun, 
milk : noun, verb, 
million : number, noun, adjective, 
millionth : 
mind : noun, verb, phrasal verb, 
mine : pronoun, noun, verb, 
mineral : noun, 
minister : noun, verb, phrasal verb, 
minute : noun, adjective, adverb, verb, 
mirror : noun, verb, 
miss : verb, phrasal verb, noun, 
mist : noun, verb, phrasal verb, 
mistake : noun, verb, phrasal verb, 
mix : verb, phrasal verb, noun, 
mixture : noun, 
model : noun, adjective, verb, 
modern : adjective, 
moment : noun, 
money : noun, 
monkey : noun, verb, phrasal verb, 
month : noun, 
monthly : adjective, adverb, noun, 
moon : noun, verb, phrasal verb, 
moral : adjective, noun, 
morals : 
more : adverb, determiner, pronoun, 
morning : noun, interjection, 
most : adverb, determiner, pronoun, 
mother : noun, verb, 
motor : noun, adjective, verb, 
mountain : noun, 
mouse : noun, 
mouth : noun, verb, phrasal verb, 
move : verb, phrasal verb, noun, 
movement : noun, 
much : adverb, determiner, pronoun, 
mud : noun, 
multiply : verb, 
murder : noun, verb, 
muscle : noun, verb, phrasal verb, 
music : noun, 
musician : noun, 
must : modal verb, noun, 
my : determiner, interjection, 
myself : pronoun, 
mysterious : adjective, adverb, 
mystery : noun, adjective, 
nail : noun, verb, phrasal verb, 
name : noun, verb, 
narrow : adjective, noun, verb, phrasal verb, 
nasty : adjective, adverb, noun, 
nation : noun, 
national : adjective, noun, 
natural : adjective, noun, 
nature : noun, 
naval : adjective, 
navy : noun, adjective, 
near : adverb, preposition, adjective, noun, verb, 
nearly : adverb, 
neat : adjective, adverb, noun, 
necessary : adjective, noun, 
neck : noun, verb, 
need : verb, noun, 
needle : noun, verb, 
negative : adjective, adverb, noun, verb, 
neighbor : noun, 
neighborhood : noun, 
neighbour : noun, 
neighbourhood : noun, 
neither : determiner, pronoun, adverb, conjunction, 
nerve : noun, verb, 
nervous : adjective, adverb, noun, 
nest : noun, verb, 
net : noun, adjective, adverb, verb, 
network : noun, verb, 
never : adverb, 
new : adjective, noun, 
news : noun, 
newspaper : noun, 
next : determiner, adjective, adverb, pronoun, 
nice : adjective, noun, 
night : noun, 
nine : number, 
ninth : adjective, pronoun, noun, 
no : adverb, determiner, noun, 
no one : pronoun, 
noble : adjective, noun, 
nobleman : noun, 
noise : noun, verb, 
non- : prefix, 
none : pronoun, adverb, 
nonsense : noun, 
nor : conjunction, adverb, 
normal : adjective, noun, 
north : noun, adjective, adverb, 
northern : adjective, 
nose : noun, verb, phrasal verb, 
not : adverb, 
note : noun, verb, phrasal verb, 
nothing : pronoun, adverb, 
notice : verb, noun, 
noticeable : adjective, adverb, 
noun : noun, 
now : adverb, conjunction, 
nowhere : adverb, 
number : noun, verb, phrasal verb, 
nurse : noun, verb, 
nut : noun, verb, 
nylon : noun, 
o'clock : adverb, 
obedient : adjective, adverb, 
obey : verb, 
object : noun, verb, 
obtain : verb, 
occasion : noun, verb, 
ocean : noun, 
odd : adjective, noun, 
of : preposition, 
off : adverb, preposition, adjective, noun, verb, 
offence : noun, 
offend : verb, 
offense : noun, 
offensive : adjective, adverb, noun, 
offer : verb, noun, 
office : noun, 
officer : noun, 
official : noun, adjective, 
often : adverb, 
oil : noun, verb, 
old : adjective, 
old-fashioned : adjective, 
on : preposition, adjective, adverb, 
once : adverb, conjunction, 
one : number, pronoun, determiner, adjective, noun, 
oneself : pronoun, 
onion : noun, 
only : adverb, adjective, conjunction, 
only just : 
onto : preposition, 
open : adjective, verb, phrasal verb, noun, 
operate : verb, 
operation : noun, 
opinion : noun, 
opponent : noun, 
opportunity : noun, 
oppose : verb, 
opposed : adjective, 
opposite : preposition, adjective, noun, adverb, 
opposition : noun, 
or : conjunction, adverb, 
orange : noun, adjective, 
order : noun, verb, phrasal verb, 
ordinary : adjective, noun, 
organ : noun, 
organise : verb, 
organization : noun, adjective, 
organize : verb, 
origin : noun, 
original : adjective, noun, 
other : determiner, adjective, pronoun, 
otherwise : adverb, 
ought : 
our : determiner, 
ours : pronoun, 
ourselves : pronoun, 
out : adverb, preposition, verb, noun, 
outdoor : adjective, 
outdoors : adverb, noun, 
outer : adjective, 
outside : adverb, preposition, adjective, noun, 
over : preposition, adverb, adjective, noun, 
owe : verb, 
owing : adjective, 
owing to : preposition, 
own : adjective, pronoun, verb, phrasal verb, 
owner : noun, 
oxygen : noun, 
pack : verb, phrasal verb, noun, 
package : noun, verb, 
packet : noun, 
page : noun, verb, phrasal verb, 
paid : 
pain : noun, verb, 
painful : adjective, 
paint : noun, verb, phrasal verb, 
painting : noun, 
pair : noun, adverb, verb, phrasal verb, 
palace : noun, 
pale : adjective, verb, noun, 
pan : noun, verb, phrasal verb, 
paper : noun, adjective, verb, 
parallel : noun, adjective, verb, 
parcel : noun, verb, phrasal verb, 
parent : noun, 
park : noun, verb, phrasal verb, 
parliament : noun, 
part : noun, verb, phrasal verb, adverb, adjective, 
participle : noun, 
particular : adjective, noun, 
partly : adverb, 
partner : noun, verb, 
party : noun, verb, 
pass : verb, phrasal verb, noun, 
passage : noun, 
passenger : noun, 
past : adjective, preposition, adverb, noun, 
pastry : noun, 
path : noun, 
patience : noun, 
patient : noun, adjective, adverb, 
pattern : noun, verb, 
pause : verb, noun, 
pay : verb, phrasal verb, noun, 
payment : noun, 
peace : noun, 
peaceful : adjective, adverb, noun, 
pen : noun, verb, phrasal verb, 
pence : noun, 
pencil : noun, verb, phrasal verb, 
people : noun, verb, 
pepper : noun, verb, 
per : preposition, 
per cent : 
percent : adjective, adverb, noun, 
perfect : adjective, verb, noun, 
perform : verb, 
performance : noun, 
perhaps : adverb, 
period : noun, adjective, 
permanent : adjective, noun, 
permission : noun, 
permit : verb, noun, 
person : noun, 
personal : adjective, 
persuade : verb, 
pet : noun, verb, adjective, 
petrol : noun, 
photograph : noun, verb, 
photography : noun, 
phrase : noun, verb, 
physical : adjective, noun, 
piano : noun, adjective, adverb, 
pick : verb, phrasal verb, noun, 
pick up : phrasal verb, 
picture : noun, verb, 
piece : noun, verb, phrasal verb, 
pig : noun, verb, phrasal verb, 
pile : noun, verb, phrasal verb, 
pilot : noun, verb, 
pin : noun, verb, phrasal verb, 
pink : adjective, noun, 
pipe : noun, verb, phrasal verb, 
pity : noun, verb, 
place : noun, verb, 
plain : adjective, noun, adverb, 
plan : noun, verb, phrasal verb, 
plane : noun, verb, adjective, 
plant : noun, verb, phrasal verb, 
plastic : noun, adjective, 
plate : noun, verb, 
play : verb, phrasal verb, noun, 
pleasant : adjective, adverb, 
please : interjection, verb, 
pleased : adjective, 
pleasure : noun, 
plenty : pronoun, adverb, noun, 
plural : noun, adjective, 
pocket : noun, verb, adjective, 
poem : noun, 
poet : noun, 
poetry : noun, 
point : noun, verb, phrasal verb, 
pointed : adjective, 
poison : noun, verb, 
poisonous : adjective, adverb, 
pole : noun, verb, 
police : noun, abbreviation, adjective, verb, 
polish : verb, noun, phrasal verb, 
polite : adjective, adverb, noun, 
political : adjective, 
politician : noun, 
politics : noun, adjective, 
pool : noun, verb, 
poor : adjective, 
popular : adjective, 
popularity : noun, 
population : noun, 
port : noun, verb, 
position : noun, verb, 
positive : adjective, noun, 
possess : verb, 
possession : noun, 
possibility : noun, 
possible : adjective, noun, 
possibly : adverb, 
post : noun, verb, 
pot : noun, verb, 
potato : noun, 
pound : noun, verb, phrasal verb, 
pour : verb, phrasal verb, 
powder : noun, verb, 
power : noun, verb, phrasal verb, adjective, 
powerful : adjective, adverb, 
practical : adjective, noun, 
practice : noun, verb, 
practise : verb, 
praise : verb, noun, 
pray : verb, adverb, 
prayer : noun, 
precious : adjective, adverb, noun, 
prefer : verb, 
preparation : noun, 
prepare : verb, 
presence : noun, 
present : adjective, verb, noun, 
preserve : verb, adjective, noun, 
president : noun, 
press : noun, verb, phrasal verb, 
pressure : noun, verb, 
pretend : verb, adjective, 
pretty : adverb, adjective, noun, 
prevent : verb, adjective, 
previous : adjective, 
price : noun, verb, 
prickly : adjective, noun, 
pride : noun, verb, 
priest : noun, 
prince : noun, 
principle : noun, 
print : verb, phrasal verb, noun, 
prison : noun, 
prisoner : noun, 
private : adjective, noun, 
prize : verb, phrasal verb, noun, adjective, 
probability : noun, 
probably : adverb, adjective, 
problem : noun, 
process : noun, verb, 
procession : noun, 
produce : verb, noun, 
product : noun, 
production : noun, 
profession : noun, 
profit : noun, verb, 
program : noun, verb, 
programme : noun, verb, 
progress : noun, verb, 
promise : verb, noun, 
pronounce : verb, 
pronunciation : noun, 
proof : noun, adjective, verb, 
proper : adjective, adverb, 
property : noun, 
proposal : noun, 
protect : verb, 
protection : noun, 
protective : adjective, adverb, noun, 
protest : noun, verb, 
proud : adjective, adverb, 
prove : verb, adjective, 
proven : adjective, 
provide : verb, phrasal verb, 
provision : noun, verb, 
provisions : 
public : adjective, noun, 
pull : verb, phrasal verb, noun, 
pump : noun, verb, phrasal verb, 
punish : verb, 
punishment : noun, 
pupil : noun, 
pure : adjective, 
purple : noun, adjective, 
purpose : noun, 
push : verb, phrasal verb, noun, 
put : verb, phrasal verb, 
quality : noun, adjective, 
quantity : noun, 
quarrel : noun, verb, phrasal verb, 
quarter : noun, verb, 
queen : noun, verb, 
question : noun, verb, 
quick : adjective, noun, interjection, adverb, 
quickly : adverb, 
quiet : adjective, noun, 
quite : predeterminer, adverb, 
rabbit : noun, verb, phrasal verb, 
race : noun, verb, 
radio : noun, verb, 
railway : noun, 
rain : noun, adjective, verb, phrasal verb, 
raise : verb, noun, 
ran : 
range : noun, verb, 
rank : noun, verb, adjective, 
rapid : adjective, noun, 
rare : adjective, 
rat : noun, verb, 
rate : noun, verb, 
rather : predeterminer, adverb, 
raw : adjective, noun, 
re- : prefix, 
reach : verb, phrasal verb, noun, 
react : verb, phrasal verb, 
reaction : noun, 
read : verb, phrasal verb, noun, 
ready : adjective, verb, noun, adverb, 
real : adjective, adverb, 
realize : verb, 
really : adverb, 
reason : noun, verb, phrasal verb, 
reasonable : adjective, noun, 
receive : verb, 
recent : adjective, 
recently : adverb, 
recognition : noun, 
recognize : verb, adjective, adverb, 
record : noun, verb, 
red : adjective, noun, 
reduce : verb, phrasal verb, 
reduction : noun, 
refusal : noun, 
refuse : verb, noun, 
regard : noun, verb, 
regular : adjective, noun, 
related : adjective, 
relation : noun, 
relationship : noun, 
relative : noun, adjective, 
relax : verb, 
relaxing : adjective, 
religion : noun, 
religious : adjective, noun, 
remain : verb, 
remark : noun, verb, 
remember : verb, 
remind : verb, phrasal verb, 
remove : verb, noun, 
rent : verb, phrasal verb, noun, 
repair : verb, phrasal verb, noun, 
repeat : verb, phrasal verb, noun, 
replace : verb, adjective, 
reply : verb, noun, 
report : noun, verb, phrasal verb, 
represent : verb, 
representative : adjective, noun, 
republic : noun, 
request : noun, verb, 
respect : noun, verb, 
respectful : adjective, adverb, noun, 
responsible : adjective, 
rest : noun, verb, phrasal verb, 
restaurant : noun, 
restrict : verb, 
result : noun, verb, phrasal verb, interjection, 
return : verb, phrasal verb, noun, adjective, 
reward : noun, verb, 
rice : noun, 
rich : adjective, 
rid : adjective, verb, phrasal verb, 
rid of : phrasal verb, 
ridden : 
ride : verb, phrasal verb, noun, 
right : adjective, noun, interjection, adverb, verb, 
ring : noun, verb, phrasal verb, 
ripe : adjective, noun, 
rise : verb, phrasal verb, noun, 
risen : 
risk : noun, verb, 
river : noun, 
road : noun, 
rob : verb, phrasal verb, 
rock : noun, verb, 
rod : noun, 
rode : 
roll : verb, phrasal verb, noun, 
romantic : adjective, adverb, noun, 
roof : noun, verb, phrasal verb, 
room : noun, verb, phrasal verb, 
root : noun, verb, phrasal verb, 
rope : noun, verb, phrasal verb, 
rose : noun, adjective, 
rough : adjective, noun, verb, phrasal verb, adverb, 
round : adverb, preposition, adjective, noun, verb, phrasal verb, 
row : noun, verb, 
royal : adjective, adverb, noun, 
rub : verb, phrasal verb, noun, 
rubber : noun, 
rude : adjective, adverb, noun, 
ruin : verb, noun, 
rule : noun, verb, phrasal verb, 
ruler : noun, 
run : verb, phrasal verb, noun, 
rush : verb, phrasal verb, noun, 
sad : adjective, 
safe : adjective, noun, interjection, 
safety : noun, 
said : adjective, 
sail : verb, phrasal verb, noun, 
sale : noun, 
salt : noun, verb, phrasal verb, adjective, 
same : adjective, pronoun, adverb, 
sand : noun, verb, 
sang : 
sank : 
sat : 
satisfaction : noun, 
satisfactory : adjective, adverb, 
satisfy : verb, 
save : verb, noun, preposition, 
saw : noun, verb, phrasal verb, 
say : verb, noun, interjection, 
scale : noun, verb, phrasal verb, 
scatter : verb, 
scene : noun, 
scenery : noun, adjective, 
school : noun, verb, 
science : noun, 
scientific : adjective, adverb, 
scientist : noun, 
scissors : noun, 
screen : noun, verb, phrasal verb, 
screw : noun, verb, phrasal verb, 
sea : noun, 
search : noun, verb, phrasal verb, 
season : noun, verb, 
seat : noun, verb, 
second : number, noun, adverb, verb, 
secrecy : noun, 
secret : adjective, adverb, noun, 
secretary : noun, 
see : verb, phrasal verb, noun, 
seed : noun, verb, 
seem : verb, 
seen : 
seize : verb, phrasal verb, 
sell : verb, phrasal verb, noun, 
send : verb, phrasal verb, 
sensation : noun, 
sense : noun, verb, 
senseless : adjective, adverb, noun, 
sensible : adjective, adverb, 
sensitive : adjective, adverb, 
sent : 
sentence : noun, verb, 
separate : adjective, adverb, verb, phrasal verb, 
series : noun, 
serious : adjective, 
servant : noun, 
serve : verb, phrasal verb, noun, 
service : noun, verb, 
set : verb, phrasal verb, noun, adjective, 
settle : verb, phrasal verb, 
seven : number, 
seventh : adjective, pronoun, noun, 
several : determiner, pronoun, adjective, adverb, 
severe : adjective, noun, 
sew : verb, phrasal verb, 
sewn : 
sex : noun, verb, phrasal verb, 
sexual : adjective, adverb, 
shade : noun, verb, phrasal verb, 
shadow : noun, verb, adjective, 
shake : verb, phrasal verb, noun, 
shaken : adjective, 
shall : modal verb, 
shame : noun, verb, 
shape : noun, verb, phrasal verb, 
share : verb, phrasal verb, noun, 
sharp : adjective, noun, adverb, 
she : pronoun, noun, 
sheep : noun, 
sheet : noun, 
shelf : noun, 
shell : noun, verb, phrasal verb, 
shelter : noun, verb, 
shelves : 
shield : noun, verb, 
shine : verb, phrasal verb, noun, 
shiny : adjective, noun, 
ship : noun, verb, 
shirt : noun, 
shock : noun, verb, adjective, 
shocking : adjective, adverb, 
shoe : noun, verb, 
shone : 
shook : 
shoot : verb, phrasal verb, noun, interjection, 
shop : noun, verb, phrasal verb, 
shopkeeper : noun, 
shore : noun, verb, phrasal verb, 
short : adjective, noun, adverb, verb, 
shot : noun, adjective, 
should : modal verb, 
shoulder : noun, verb, 
shout : verb, phrasal verb, noun, 
show : verb, phrasal verb, noun, 
shown : 
shut : verb, phrasal verb, adjective, 
shy : adjective, adverb, noun, verb, phrasal verb, 
sick : adjective, noun, verb, phrasal verb, 
side : noun, adjective, verb, 
sideways : adverb, adjective, 
sight : noun, verb, 
sign : noun, verb, phrasal verb, 
signal : noun, verb, adjective, 
signature : noun, 
silence : noun, verb, 
silent : adjective, adverb, 
silk : noun, 
silly : adjective, noun, 
silver : noun, adjective, verb, 
similar : adjective, preposition, 
similarity : noun, 
simple : adjective, 
since : preposition, conjunction, adverb, 
sincere : adjective, 
sing : verb, phrasal verb, 
single : adjective, noun, verb, phrasal verb, 
singular : adjective, noun, 
sink : verb, phrasal verb, noun, adjective, 
sister : noun, 
sit : verb, phrasal verb, 
situation : noun, 
six : number, 
sixth : adjective, pronoun, noun, 
size : noun, verb, phrasal verb, 
skies : 
skilful : adjective, adverb, 
skill : noun, 
skillful : adjective, adverb, 
skin : noun, verb, phrasal verb, 
skirt : noun, verb, 
sky : noun, 
slave : noun, verb, 
sleep : verb, phrasal verb, noun, 
slept : 
slid : 
slide : verb, noun, 
slight : adjective, verb, noun, 
slip : verb, phrasal verb, noun, 
slippery : adjective, noun, 
slope : noun, verb, phrasal verb, 
slow : adjective, noun, verb, phrasal verb, adverb, 
small : adjective, adverb, noun, 
smell : noun, verb, phrasal verb, 
smile : verb, noun, 
smoke : noun, verb, phrasal verb, 
smooth : adjective, noun, verb, phrasal verb, 
snake : noun, verb, 
snow : noun, verb, 
so : adverb, conjunction, noun, 
soap : noun, verb, 
social : adjective, adverb, noun, 
society : noun, 
sock : noun, verb, phrasal verb, 
soft : adjective, adverb, noun, 
soil : noun, verb, adjective, 
sold : 
soldier : noun, verb, phrasal verb, 
solemn : adjective, adverb, 
solid : adjective, adverb, noun, 
solution : noun, 
solve : verb, adjective, 
some : determiner, pronoun, adverb, 
somebody : pronoun, noun, 
somehow : adverb, 
someone : pronoun, noun, 
someplace : adverb, 
something : pronoun, 
sometimes : adverb, 
somewhere : adverb, 
son : noun, 
song : noun, 
soon : adverb, 
sore : adjective, noun, 
sorrow : noun, verb, 
sorry : adjective, 
sort : noun, verb, phrasal verb, 
soul : noun, 
sound : noun, verb, phrasal verb, adjective, adverb, 
soup : noun, verb, phrasal verb, 
sour : adjective, adverb, noun, verb, 
south : noun, adjective, adverb, 
southern : adjective, 
space : noun, verb, 
spacecraft : noun, 
spade : noun, 
speak : verb, phrasal verb, 
spear : noun, verb, 
special : adjective, noun, 
specialist : noun, 
specific : adjective, noun, 
speech : noun, 
speed : noun, verb, phrasal verb, 
spell : verb, phrasal verb, noun, 
spelled : 
spend : verb, 
spent : adjective, 
spin : verb, phrasal verb, noun, 
spirit : noun, verb, phrasal verb, 
spite : noun, verb, 
splendid : adjective, adverb, 
split : verb, phrasal verb, noun, 
spoil : verb, noun, 
spoiled : adjective, 
spoke : noun, 
spoken : adjective, 
spoon : noun, verb, 
sport : noun, verb, 
spot : noun, verb, adjective, 
sprang : 
spread : verb, phrasal verb, noun, adjective, 
spring : noun, verb, phrasal verb, 
sprung : adjective, 
spun : 
square : adjective, noun, verb, phrasal verb, adverb, 
stage : noun, verb, 
stair : noun, 
stamp : noun, verb, phrasal verb, 
stand : verb, phrasal verb, noun, 
standard : noun, adjective, 
star : noun, verb, 
start : verb, phrasal verb, noun, 
state : noun, verb, 
statement : noun, verb, adjective, 
station : noun, verb, 
stay : verb, phrasal verb, noun, 
steady : adjective, adverb, noun, verb, interjection, 
steal : verb, noun, 
steam : noun, verb, phrasal verb, 
steel : noun, verb, 
steep : adjective, adverb, noun, verb, 
stem : noun, verb, phrasal verb, 
step : noun, verb, phrasal verb, 
stick : verb, phrasal verb, noun, 
sticky : adjective, noun, 
stiff : adjective, adverb, noun, verb, 
still : adverb, adjective, noun, verb, 
sting : verb, noun, 
stitch : noun, verb, phrasal verb, 
stole : noun, 
stolen : adjective, 
stomach : noun, verb, 
stone : noun, verb, 
stood : 
stop : verb, phrasal verb, noun, 
store : noun, verb, 
storm : noun, verb, 
story : noun, 
straight : adverb, adjective, noun, 
strange : adjective, noun, adverb, 
stranger : noun, 
stream : noun, verb, 
street : noun, 
strength : noun, 
stretch : verb, phrasal verb, noun, adjective, 
strict : adjective, noun, 
strike : verb, phrasal verb, noun, 
string : noun, verb, phrasal verb, 
stroke : noun, verb, 
strong : adjective, 
struck : adjective, 
structure : noun, verb, 
struggle : verb, phrasal verb, noun, 
stuck : adjective, 
student : noun, 
study : noun, verb, phrasal verb, 
stung : 
stupid : adjective, adverb, noun, 
style : noun, verb, 
subject : noun, adjective, verb, phrasal verb, 
substance : noun, 
subtract : verb, 
succeed : verb, phrasal verb, 
success : noun, 
successful : adjective, adverb, 
such : determiner, predeterminer, pronoun, 
suck : verb, phrasal verb, noun, 
sudden : adjective, noun, 
suffer : verb, 
sugar : noun, verb, adjective, 
suggest : verb, 
suit : noun, verb, 
suitable : adjective, 
sum : noun, verb, phrasal verb, 
summer : noun, verb, 
sun : noun, verb, 
sung : 
sunk : 
supper : noun, 
supply : noun, verb, 
support : verb, noun, 
suppose : verb, 
sure : adjective, noun, verb phrase, verb, adverb, 
surface : noun, verb, adjective, 
surprise : noun, verb, 
surprising : adjective, 
surround : verb, noun, 
swallow : verb, phrasal verb, noun, 
swam : 
swear : verb, noun, phrasal verb, 
sweep : verb, phrasal verb, noun, 
sweet : adjective, adverb, noun, 
swell : verb, noun, adjective, 
swept : 
swim : verb, noun, 
swing : verb, phrasal verb, noun, 
swollen : adjective, 
sword : noun, 
swore : 
sworn : adjective, 
swum : 
swung : 
sympathetic : adjective, adverb, 
sympathy : noun, 
system : noun, 
table : noun, verb, 
tail : noun, verb, phrasal verb, 
take : verb, phrasal verb, noun, 
taken : 
talk : verb, phrasal verb, noun, 
tall : adjective, noun, 
taste : noun, verb, 
taught : 
tax : noun, verb, phrasal verb, 
taxi : noun, verb, 
tea : noun, 
teach : verb, 
team : noun, verb, phrasal verb, 
tear : noun, verb, phrasal verb, 
technical : adjective, 
teeth : 
telephone : noun, verb, 
television : noun, 
tell : verb, phrasal verb, 
temper : noun, verb, 
temperature : noun, 
temple : noun, 
temporary : adjective, adverb, 
ten : number, noun, 
tend : verb, 
tendency : noun, 
tender : adjective, adverb, noun, verb, 
tennis : noun, 
tense : adjective, adverb, noun, verb, 
tent : noun, 
terrible : adjective, 
terror : noun, 
test : noun, verb, 
than : conjunction, preposition, 
thank : verb, 
that : determiner, pronoun, conjunction, adverb, 
the : definite article, determiner, adverb, 
theater : noun, 
theatre : noun, 
their : determiner, 
theirs : pronoun, 
them : pronoun, determiner, 
themselves : pronoun, 
then : adverb, adjective, 
there : pronoun, adverb, interjection, 
therefore : adverb, 
these : 
they : pronoun, 
thick : adjective, adverb, noun, 
thief : noun, 
thieves : 
thin : adjective, noun, adverb, verb, 
thing : noun, 
think : verb, phrasal verb, noun, 
third : adjective, pronoun, adverb, noun, 
thirst : noun, verb, phrasal verb, 
thirsty : adjective, adverb, 
this : determiner, pronoun, adverb, 
thorough : adjective, noun, 
those : 
though : conjunction, adverb, 
thought : noun, 
thousand : number, adjective, noun, 
thousandth : 
thread : noun, verb, 
threat : noun, 
threaten : verb, 
threatening : adjective, adverb, 
three : number, 
threw : 
throat : noun, 
through : preposition, adverb, conjunction, adjective, 
throw : verb, phrasal verb, noun, 
thrown : 
thumb : noun, verb, phrasal verb, 
thunder : noun, verb, 
thus : adverb, 
ticket : noun, verb, 
tidy : adjective, adverb, noun, verb, phrasal verb, 
tie : verb, phrasal verb, noun, 
tiger : noun, 
tight : adjective, adverb, noun, 
time : noun, verb, 
timetable : noun, verb, 
tin : noun, adjective, 
tire : verb, phrasal verb, noun, 
tired : adjective, noun, adverb, 
tiring : adjective, 
title : noun, 
to : preposition, adverb, 
tobacco : noun, 
today : adverb, noun, 
toe : noun, verb, 
together : adverb, adjective, 
toilet : noun, 
told : 
tomorrow : adverb, noun, 
tongue : noun, verb, 
tonight : adverb, noun, 
too : adverb, 
took : 
tool : noun, verb, phrasal verb, 
tooth : noun, 
top : noun, adjective, verb, phrasal verb, 
tore : 
torn : 
total : adjective, noun, verb, phrasal verb, 
touch : verb, phrasal verb, noun, 
tour : noun, verb, 
tourist : noun, 
towards : preposition, 
tower : noun, verb, 
town : noun, adjective, 
toy : noun, verb, phrasal verb, adjective, 
track : noun, verb, phrasal verb, 
trade : noun, verb, phrasal verb, 
traditional : adjective, adverb, 
traffic : noun, verb, phrasal verb, 
train : noun, verb, 
training : noun, 
translate : verb, adjective, 
transparent : adjective, adverb, 
trap : noun, verb, 
travel : verb, noun, 
treat : verb, noun, 
treatment : noun, 
tree : noun, adjective, 
tremble : verb, noun, 
tribe : noun, 
trick : noun, verb, adjective, 
tried : adjective, 
tries : 
trip : noun, verb, phrasal verb, 
tropical : adjective, 
trouble : noun, verb, 
trousers : noun, adjective, 
true : adjective, adverb, noun, 
trunk : noun, 
trust : noun, verb, phrasal verb, 
truth : noun, 
try : verb, phrasal verb, noun, 
tube : noun, verb, 
tune : noun, verb, phrasal verb, 
turn : verb, phrasal verb, noun, 
twice : adverb, predeterminer, noun, 
twist : verb, noun, adjective, 
two : number, noun, adverb, 
tying : 
type : noun, verb, 
typical : adjective, 
tyre : noun, 
ugly : adjective, noun, 
un- : prefix, 
uncle : noun, 
under : preposition, adverb, 
understand : verb, 
understood : 
underwear : noun, 
undid : 
undo : verb, 
undoes : 
undone : adjective, 
unexpected : adjective, adverb, 
uniform : noun, adjective, adverb, 
union : noun, 
unit : noun, 
unite : verb, 
universal : adjective, adverb, noun, 
universe : noun, 
university : noun, 
unless : conjunction, 
until : preposition, conjunction, 
unusual : adjective, 
up : adverb, preposition, adjective, noun, verb, 
upper : adjective, noun, 
upright : adjective, adverb, noun, 
upset : adjective, verb, noun, 
upside : noun, preposition, 
upside down : adverb, adjective, 
upstairs : adverb, adjective, noun, 
urge : verb, phrasal verb, noun, 
urgent : adjective, noun, adverb, 
us : pronoun, 
use : verb, phrasal verb, noun, 
useful : adjective, adverb, 
useless : adjective, adverb, noun, 
using : 
usual : adjective, 
usually : adverb, 
valley : noun, 
valuable : adjective, 
value : noun, verb, adjective, 
variety : noun, 
various : adjective, 
vary : verb, 
vegetable : noun, adjective, 
vehicle : noun, 
verb : noun, 
very : adverb, adjective, 
victory : noun, 
view : noun, verb, 
village : noun, 
violence : noun, 
violent : adjective, 
visit : verb, phrasal verb, noun, 
voice : noun, verb, 
vote : verb, phrasal verb, noun, 
vowel : noun, 
voyage : noun, verb, 
wages : 
waist : noun, 
wait : verb, phrasal verb, noun, 
waiter : noun, 
wake : verb, phrasal verb, noun, 
walk : verb, phrasal verb, noun, 
wall : noun, verb, phrasal verb, 
wander : verb, noun, 
want : verb, phrasal verb, noun, 
war : noun, 
warm : adjective, noun, verb, phrasal verb, adverb, 
warmth : noun, 
warn : verb, phrasal verb, 
warning : noun, adjective, 
was : 
wash : verb, phrasal verb, noun, 
waste : noun, verb, phrasal verb, adjective, 
watch : verb, phrasal verb, noun, 
water : noun, verb, phrasal verb, 
wave : noun, verb, phrasal verb, 
way : noun, adverb, 
we : pronoun, 
weak : adjective, adverb, 
wealth : noun, 
weapon : noun, 
wear : verb, adjective, phrasal verb, noun, 
weather : noun, verb, 
weave : verb, noun, 
wedding : noun, 
week : noun, 
weekly : adjective, adverb, noun, 
weigh : verb, phrasal verb, 
weight : noun, verb, 
welcome : verb, adjective, noun, interjection, 
well : adverb, interjection, adjective, noun, verb, 
went : 
were : 
west : noun, adjective, adverb, 
western : adjective, noun, 
wet : adjective, adverb, noun, verb, 
what : pronoun, determiner, predeterminer, 
whatever : determiner, pronoun, adverb, 
wheat : noun, 
wheel : noun, verb, phrasal verb, 
when : adverb, conjunction, pronoun, 
whenever : adverb, conjunction, 
where : adverb, conjunction, pronoun, 
whether : conjunction, 
which : determiner, pronoun, 
whichever : determiner, pronoun, 
while : conjunction, noun, verb, 
whip : verb, phrasal verb, noun, 
whisper : verb, noun, 
whistle : verb, noun, 
white : adjective, noun, verb, phrasal verb, 
who : pronoun, 
whoever : pronoun, 
whole : adjective, noun, 
whom : pronoun, 
whose : determiner, pronoun, 
why : adverb, interjection, noun, 
wicked : adjective, adverb, noun, 
wide : adjective, adverb, 
widespread : adjective, 
width : noun, 
wife : noun, 
wild : adjective, noun, adverb, 
will : modal verb, noun, 
willing : adjective, adverb, noun, 
win : verb, phrasal verb, noun, 
wind : noun, verb, phrasal verb, 
window : noun, 
wine : noun, verb, 
wing : noun, verb, 
winter : noun, verb, 
wire : noun, verb, 
wisdom : noun, 
wise : adjective, adverb, verb, phrasal verb, suffix, 
wish : verb, phrasal verb, noun, 
with : preposition, 
within : preposition, adverb, 
without : preposition, adverb, 
witness : noun, verb, 
wives : 
woman : noun, 
women : 
won : noun, 
wonder : verb, noun, adjective, 
wood : noun, 
wooden : adjective, adverb, noun, 
wool : noun, 
woolen : adjective, 
woollen : adjective, 
word : noun, verb, 
wore : verb, 
work : verb, phrasal verb, noun, 
world : noun, adjective, 
worm : noun, verb, phrasal verb, 
worn : adjective, 
worry : verb, phrasal verb, noun, 
worse : adjective, noun, adverb, 
worship : verb, noun, 
worst : adjective, noun, adverb, 
worth : preposition, noun, 
worthy : adjective, noun, 
would : modal verb, 
wound : noun, verb, 
wove : 
woven : 
wrap : verb, phrasal verb, noun, 
wreck : verb, noun, 
wrist : noun, 
write : verb, phrasal verb, 
written : adjective, 
wrong : adjective, adverb, noun, verb, 
wrongdoing : noun, 
wrote : 
yard : noun, 
year : noun, 
yearly : adjective, adverb, 
yellow : adjective, noun, verb, 
yes : adverb, noun, adjective, 
yesterday : adverb, noun, 
yet : adverb, conjunction, 
you : pronoun, 
young : adjective, noun, 
your : determiner, 
yours : pronoun, 
yourself : pronoun, 
youth : noun, 
zero : number, verb, phrasal verb`;